### ISSUE TITLE
The sort buttons locations should be switched

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#10]
```
1996   /  2015
--->  /   <---
```

`2015` should be a dynamic value taken from the latest entry date

**Comment by mushon** [comment]
http://prntscr.com/6sfqlr

**Comment by mushon** [comment]
this was not addressed

**Comment by mushon** [comment]
@RTLcoil as a best practice, please do not close issues I opened. Instead reassign them back to me and let me check and close them. Thanks ;)

**Comment by YomesInc** [comment]
Sort default  http://prntscr.com/6w6xij 
After sorting  http://prntscr.com/6w6xph
we also recommend to enable both sides of the sorting buttons, not just the left one

**Comment by mushon** [comment]
Cool
