### ISSUE TITLE
Artist name on list should work as link and hover

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#13]
(not only the image should be clickable/hoverable)

**Comment by YomesInc** [comment]
Please explain what you mean here

**Comment by mushon** [comment]
the text on the lists should be clickable:
http://prntscr.com/6tdtws

**Comment by YomesInc** [comment]
Check it.

**Comment by mushon** [comment]
@RTLcoil the pop-over element should appear on hover too it should function exactly the same as the icon

**Comment by YomesInc** [comment]
Please explain

**Comment by mushon** [comment]
basically the hovering the text should function exactly the same like hovering the image, as if they are exactly the same link. when I hover the image or the text the pop-over card should appear. when I click the image or the text it should take me to that page.

**Comment by YomesInc** [comment]
Check it.
