### ISSUE TITLE
Humbureger icon animation wasn't implemented

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#19]
http://prntscr.com/6sfnpq

**Comment by YomesInc** [comment]
Like I wrote you at some other place, the animation is there, it's just triggered when it is still invisible and I'm not sure we can trigger it when it is located only in the visible part of the screen. Please advise.

**Comment by mushon** [comment]
maybe you should simply reload it by removing and adding it immediately. I'm not sure what should be the best way to do it.

**Comment by YomesInc** [comment]
I can offer to make the animation on css for the left part. The text will stay the same - .svg. If you're OK with this, I need a new .svg for that, with text only.

**Comment by mushon** [comment]
Sure, if it achieves the desired result, definitely go for it.

**Comment by YomesInc** [comment]
I need the .SVG like I wrote above, to move forward here please.

**Comment by mushon** [comment]
uploaded: a667bdfcccfc2601fa0b9d6eec8722395205289c

**Comment by YomesInc** [comment]
Did you upload the SVG?

**Comment by mushon** [comment]
I have, it's here: a667bdfcccfc2601fa0b9d6eec8722395205289c

**Comment by YomesInc** [comment]
I see... I've checked it and we did it slightly differently.

Now you can open the menu on pages with the slider, such as the main http://prntscr.com/7kez7s

Menu is opened during the scroll - http://prntscr.com/7kfa8j
and stays as a fixed background - (opened http://prntscr.com/7kfap4 closed http://prntscr.com/7kf0jh)

We've also made it in a way so it would work on pages with or without upper slider, like here http://demo.rtl.co.il/turbulence/commission/tributaries-text-fed-streams-a-feed-reading-of-the-capilano-review-by-j-r-carpenter/

or here http://demo.rtl.co.il/turbulence/commission/disco-nnect/

**Comment by mushon** [comment]
Ok thanks
