### ISSUE TITLE
commission popover is lacking the arrow on desktop

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#24]
http://prntscr.com/6u0x6e
Please note, this arrow is missing only on desktop, it doesn't need to appear on mobile.

I recommend using this technique to implement it:
https://css-tricks.com/snippets/css/css-triangle/

**Comment by YomesInc** [comment]
Check it.

**Comment by mushon** [comment]
good, please just fix the z-index so the hover icon won't cover the popover's frame

**Comment by YomesInc** [comment]
As before, it would be helpful to see a screenshot.

**Comment by mushon** [comment]
true. here you go: http://prntscr.com/6v7o1l

**Comment by YomesInc** [comment]
tnx

**Comment by YomesInc** [comment]
Check it.

**Comment by mushon** [comment]
Add one more pixel to the arrow width (like this):

```
.i-item.side-right .i-item__popup.i-item__popup_custom-color::before {
    border-width: 9px;
    margin-top: -4px;
}
```

**Comment by mushon** [comment]
done
