### ISSUE TITLE
Create default user-profile

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#26]

**Comment by YomesInc** [comment]
Not sure what this ticket means

**Comment by mushon** [comment]
It’s assigned to me ;)

-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On May 3, 2015 at 5:20:28 PM, RTLcoil (notifications@github.com) wrote:

Not sure what this ticket means

**Comment by YomesInc** [comment]
Oh, sorry, I've got a notification and didn't pay attention.
