### ISSUE TITLE
Sub-title field (in commissions) should appear under the title

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#27]

**Comment by YomesInc** [comment]
Please attach screenshots

**Comment by mushon** [comment]
http://prntscr.com/711s0l

**Comment by YomesInc** [comment]
It is only used for this slider at the moment: http://gyazo.com/39ef2b7e56056240635cea20d1af505f

To use it in other places - please send me URLs of those pages you would like to see it there and also let me know if you have any preference in terms of HTML tag you would like to see it in.

**Comment by mushon** [comment]
Ok, scratch that.
It was my mistake.

I might want to add an optional subheading that would indeed appear under commission titles, but I think I’ll do it myself after you guys are done.

**Comment by YomesInc** [comment]
Cool, so I'm assigning it to you for now.

**Comment by mushon** [comment]
Yeap. Thanks.
