### ISSUE TITLE
Support the date picker for choosing a launch date

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#28]

**Comment by YomesInc** [comment]
Not sure what this ticket means, please explain.

**Comment by mushon** [comment]
I switched to the more correct and date standards compliant date picker widget: http://prntscr.com/711qni
You should account for it in the code to prevent things [like this](http://prntscr.com/711rcc) from happening

**Comment by YomesInc** [comment]
Mushon, I am not only spending lots of my personal time on this, but also loosing actual money on this project, which I am paying to my developers and will never get back.

I ask you to eliminate such changes on the go and also describe tasks properly, with screenshots and a lot of details, avoiding me to re-ask what is it and where is it.

**Comment by mushon** [comment]
Fair enough, will do my best.

**Comment by YomesInc** [comment]
Thanks Mushon

**Comment by mushon** [comment]
This was implemented by me. Done.
