### ISSUE TITLE
Resize images to fit expected sizes

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#29]
Use WP's thumbnailing

**Comment by YomesInc** [comment]
That's what it does. If it doesn't work at some place - please send me a link and we'll fix.

**Comment by mushon** [comment]
HP hovers: http://prntscr.com/711ook
Image stretched here: http://prntscr.com/711p8j (the images should never stretch)

**Comment by YomesInc** [comment]
http://prntscr.com/711ook - it's done here
http://prntscr.com/711p8j -  here the image should be bigger, it's 420 pixels, so it is stretched on larger screens.

**Comment by mushon** [comment]
In both cases the images should be cropped to size (either using overflow: hidden or by cropping the original image) rather than stretched or resized to fit.

**Comment by YomesInc** [comment]
Could you check now please?

**Comment by mushon** [comment]
icon hover - not quite there yet: http://prntscr.com/73s8xt
& the image here is still stretched wider than [the original](http://demo.rtl.co.il/turbulence/wp-content/uploads/2015/04/slide_min-4.jpg): http://prntscr.com/73sao8

**Comment by YomesInc** [comment]
Please check if everything's OK

**Comment by mushon** [comment]
still…
http://prntscr.com/75erxh

**Comment by mushon** [comment]
http://prntscr.com/75escg
+this should be full framed, either through a crop or by using a background color (not by stretching the image)

**Comment by YomesInc** [comment]
So you would like an option to pick a color for each commission as well as for the main page?

**Comment by mushon** [comment]
Correct, this is based on the featured image, not the commission frame color

**Comment by YomesInc** [comment]
Please take a look

**Comment by YomesInc** [comment]
http://gyazo.com/4e9cdba7a8f2e58fa01f3dc56605aa47 - HP
http://gyazo.com/925721fb2849f00fe2b7177294570ede - Commission

**Comment by mushon** [comment]
That's good, thanks.
Still a full crop of the thumbnails is still required. Try playing with the `max-height:100%` property
http://prntscr.com/76jep6
http://prntscr.com/76jejy

(same case in the commission popover square)

**Comment by YomesInc** [comment]
And by full crop you mean to fill the whole space like you showed here http://prntscr.com/76jejy ?

**Comment by mushon** [comment]
Yeap :)

**Comment by YomesInc** [comment]
Could you check if it's OK now?

**Comment by mushon** [comment]
it's ok
