### ISSUE TITLE
Sliding menu issues

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#3]
- [x] The menu should be fixed and fill the page's height
- [x] It should also slide into the frame under the logo from the left
- [ ] The turburger.svg file should be used for that too
- [x] In mobile - the search bar should appear fixed to the bottom (the content should scroll under it)
- [x] In mobile - the share icons should appear like in the "we socialize" in the footer.

**Comment by YomesInc** [comment]
"It should also slide into the frame under the logo from the left"
Could you send a print screen for that?

**Comment by mushon** [comment]
I'm referring to the side menu's interaction. 
Its not something you can explain with a print screen really as its animated. It should mimic the "reveal" function of the homepage but appear from left to right as if the menu with the logo appearing exactly on top of the existing logo are overlaid on top and are masked in from left to right with a `overflow: hidden` kind of effect. Let me know if this makes sense. Thanks.

**Comment by YomesInc** [comment]
Cool, could you you send me two images then - its starting and ending positions?

**Comment by mushon** [comment]
The menu is revealed under the logo. Maybe this would help explain:
![turb_menu_slide](https://cloud.githubusercontent.com/assets/27123/6863754/04166396-d468-11e4-96f9-d4ecebb0f817.png)

**Comment by mushon** [comment]
this is not closed

**Comment by YomesInc** [comment]
Then I will need further explanation on this, sorry - I do not understand what is required.

**Comment by mushon** [comment]
The slider opens under the content rather than reveal it. See:
http://prntscr.com/6tzo9l

(I'm testing on Firefox 37, assuming the code is consistent across modern browsers)

**Comment by YomesInc** [comment]
Got it, thanks

**Comment by YomesInc** [comment]
Check it

**Comment by mushon** [comment]
Almost there… Scrolling up should not make the panel disappear.

**Comment by YomesInc** [comment]
It's one of the bugs in all browsers based on chromium which is described here: https://code.google.com/p/chromium/issues/detail?id=335442. We've applied a fix for this particular case, because applying it to all the site at once can create unpredictable problems, such as this one: http://prntscr.com/72u11u

**Comment by mushon** [comment]
What I meant is that when you scroll up from [this state](http://prntscr.com/73seam) the menu disappears, and it shouldn't do that.

**Comment by YomesInc** [comment]
ok, I would like to clarify then. The menu should be shown when the site is in this position http://prntscr.com/741l0p and should be called when one presses on the hamburger on the left? Because right now there are two types, at the top of the HP and on the commission page, just without the menu. While if you scroll one screen down and the slider goes upwards (hides from the view), then the second logo appears, and THERE when one clicks we can show the menu.
Please let me know

**Comment by mushon** [comment]
These are two separate issues.
Firstly, the menu should never disappear unless I asked it to disappear (by clicking the hamburger or clicking anywhere outside of the menu). Right now scrolling up when the menu is open closes it.

Secondly, you are right to call me out on my choice to have the logo double as a hamburger button, it gets confusing. What I would like to do is to add a hamburger button to the left of the logo and give up on this nice but unfriendly doubling idea. I don't want you guys to work on it too much. I'll do the CSS for it. I would only ask for you to add an `<a href="#" class="hamburger></a>` element to the left of the logo and I will style it myself. The `.hamburger` element will slide the menu in and the logo will return us to the main page. After you implement that you can reassign to me and I will implement the hamburger's css. Would that be ok?

**Comment by mushon** [comment]
>  Firstly, the menu should never disappear unless I asked it to disappear (by clicking the hamburger or clicking anywhere outside of the menu). Right now scrolling up when the menu is open closes it.

This has not been fixed yet

**Comment by YomesInc** [comment]
Could you check if it's fine now?

**Comment by mushon** [comment]
Great!
