### ISSUE TITLE
How do we enter the top images to the commission page?

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#30]

**Comment by YomesInc** [comment]
These are the same pictures as on the main, just with an author for this particular comission

**Comment by mushon** [comment]
What I mean is how do we include multiple pictures for each commission to appear in the commission gallery?

**Comment by YomesInc** [comment]
If current project's author is Sam Cook, then there would be shown other Sam's projects.

**Comment by mushon** [comment]
Just to make sure we’re on the same page, I’m referring to the large header image gallery at the top of the commission pages.
This gallery should slide through multiple images & videos for each commission.

**Comment by YomesInc** [comment]
Could you purchase this one http://www.advancedcustomfields.com/add-ons/repeater-field/ ?

**Comment by mushon** [comment]
I approve it.
You can buy it and add the cost to the next invoice. That way you could keep the multi-site license for future projects.

**Comment by YomesInc** [comment]
Thanks

**Comment by YomesInc** [comment]
Done http://gyazo.com/928cf0eff31e1906b0ff9981b6344e32

**Comment by mushon** [comment]
Good
