### ISSUE TITLE
Add dropdown for choosing the platform icon (desktop, mobile, tablet…)

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#31]

**Comment by YomesInc** [comment]
Screenshot please

**Comment by mushon** [comment]
The modern desktop is just one of the options for the platform icon as it appears on the homepage:
http://prntscr.com/711kkm

and in the commission page here:
http://prntscr.com/711kyl

The full list as it appears here:
https://projects.invisionapp.com/d/main#/console/2403969/55528211/preview

 includes:
- Vintage PC
- 90s imac
- 90s PC
- Flat Screen
- Laptop
- Smartphone Portrait
- Smartphone Landscape
- HiRes Screen

**Comment by YomesInc** [comment]
![qibw4ms](https://cloud.githubusercontent.com/assets/1785648/7555952/896e3a62-f733-11e4-9baf-c556c72e9ed9.png)
Could you identify each icon with each type of the above?

**Comment by mushon** [comment]
4 / scrn-Power_Mac_5000 = ico-vintage-pc
1 / scrn-crt_screen = ico-90-pc
ico-flat-screen = scrn-flat-screen
…
…
…
ico-hires-screen = scrn-wide_screen

**Comment by RTLcoil** [comment]
Please check

**Comment by YomesInc** [comment]
Sorry, this one is not done yet

**Comment by YomesInc** [comment]
Here are the classes and the devices, please check if they are implemented well on the website and let me know if anything.

Vintage PC = i-item_scrn-Power_Mac_5000
90s imac = i-item_scrn-imac_G3
90s PC = i-item_scrn-crt_screen
Flat Screen = ico-flat-screen
Laptop = i-item_scrn-laptop
Smartphone Portrait = i-item_scrn-smartphone
Smartphone Landscape = i-item_scrn-smartphone_horizontal
HiRes Screen =  i-item_scrn-wide_screen

**Comment by mushon** [comment]
On the homepage it seems like the classes are assigned but the images are missing:
http://prntscr.com/75ryhd

+the icon should change in the hover effect on the commission pages too:
http://prntscr.com/75rx33

**Comment by YomesInc** [comment]
Mushon, please take a look and let me know if it's good or you'd prefer it to be 180 х 180, like on the main commissions preview http://prntscr.com/772y9t 
Referring to this http://demo.rtl.co.il/turbulence/commission/i-sky-tv/    http://prntscr.com/772zmo

**Comment by mushon** [comment]
The max height (or max-width if the image is tall) should be 180px. Like this: http://prntscr.com/77mbsl
The hover should crop the image like this: http://prntscr.com/77mclv

**Comment by YomesInc** [comment]
Please check

**Comment by mushon** [comment]
This is good, please don't forget to also add the tablet screen

**Comment by YomesInc** [comment]
Which one of these is tablet?

Vintage PC
90s imac
90s PC
Flat Screen
Laptop
Smartphone Portrait
Smartphone Landscape
HiRes Screen

**Comment by mushon** [comment]
Look at the assets folder in Invision. It was there but you simply forgot to include it.

**Comment by YomesInc** [comment]
Got it, I think it was fixed - there was a problem in the code.

**Comment by mushon** [comment]
yeap
