### ISSUE TITLE
Use this styled Gmap and keep to zoom 5

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#33]
http://www.mapstylr.com/style/turbulence/

(documentation inside)

**Comment by YomesInc** [comment]
Why is this crucial?

**Comment by mushon** [comment]
Have you seen how it looks otherwise?
http://prntscr.com/73t74l

Also please make sure to hide the map interface (zoom, street view, map options, dragging…). It should be a static map.

**Comment by YomesInc** [comment]
Done

**Comment by mushon** [comment]
Cool, the map is right.
Please just make sure that it is centered as right now resizing the screen moves the marker and loses sync with the map: http://prntscr.com/74nmoj

**Comment by mushon** [comment]
This is possibly related to the report above. In both the artists pages and the commissions pages the maps marker is out of sync with the chosen location in the admin: http://prntscr.com/74nnom
This is also effected badly by responsive breakpoints.

**Comment by YomesInc** [comment]
Looks better now, please check and let me know if anything.

**Comment by mushon** [comment]
The marker out-of-sync with map issue is still the same.

**Comment by YomesInc** [comment]
If you look on NY it's because it captures the state rather than a city. Either specify the location or provide me with another "bad" example so that I'd look into it.

**Comment by mushon** [comment]
This is the problem I'm referring to:
![markerbug](https://cloud.githubusercontent.com/assets/27123/7685420/d4202df4-fd96-11e4-9aee-4d66181a186f.gif)
[See it here](http://demo.rtl.co.il/turbulence/artist/jeff-thompson/)

**Comment by YomesInc** [comment]
This only happens when you resize the browser manually. We only re-count and set the location when the page is loaded, so if you resize and refresh - you'll see that it's back to normal.

**Comment by mushon** [comment]
It also happens when the mobile screen reorients and in general it is imprecise (it doesn't point where it's supposed to). The image should be centered within its frame and the profile pic's line should be anchored to the map center.

**Comment by YomesInc** [comment]
Unfortunately that's the best result I can achieve within the given timeframe. I do not have resources for this project to make it perfect, sorry Mushon, I understand that it can be improved but considering our situation it is good as it is.

**Comment by mushon** [comment]
It's a simple fix as described here:
http://stackoverflow.com/questions/8792676/center-google-maps-v3-on-browser-resize-responsive

If you'd rather not do it, reassign it to me and I will apply it when you're done.

**Comment by YomesInc** [comment]
I prefer not to get into this, so assigning to you.
Thanks

**Comment by mushon** [comment]
Closing this and documenting alignment error in #47
