### ISSUE TITLE
Artists hover profile pic should be clickable

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#36]
http://prntscr.com/74nkml
A much simpler implementation would be to use [Google's static map API](https://developers.google.com/maps/documentation/staticmaps/) that simply returns an image. Same goes for issue #33

**Comment by mushon** [comment]
Correction: i see the new map style there and no interface. Can we just make sure the profile pick is clickable?

**Comment by YomesInc** [comment]
Sure, please check

**Comment by mushon** [comment]
Great!
