### ISSUE TITLE
The text on the image gallery should be the commisison title, not the image title

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#39]
This: http://i.imgur.com/gfGN95T.png
From: http://demo.rtl.co.il/turbulence/commission/furious-7/
Should say: INTERP

It should also be attached to the bottom (60px) of the screen, like this: http://prntscr.com/77mgyl

**Comment by YomesInc** [comment]
Could you verify from where to where the distance should be? From the bottom of the text? If yes - to which element beneath it?
http://prntscr.com/7abn5y

**Comment by mushon** [comment]
Please pull my code. The positioning is something I already took care of yesterday. But it seems like the code on the site isn't synced with the Github repo

**Comment by YomesInc** [comment]
Could you resolve this conflict instead?

**Comment by mushon** [comment]
You haven't committed the code that's on the site so I can't resolve it.

**Comment by YomesInc** [comment]
Got you, where I can find your changes?

**Comment by mushon** [comment]
They're in the GH-pages branch. Just do a diff

Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

**Comment by YomesInc** [comment]
Could you specify the exact commit which we've overwritten?

**Comment by mushon** [comment]
https://github.com/RTLcoil/Turbulence/commit/6584fb556b3b8e5e923c108b0e2f1bd4d843432c
The sooner you can re-add these overwritten changes, the better

**Comment by YomesInc** [comment]
I suppose this can be closed

**Comment by mushon** [comment]
yes
