### ISSUE TITLE
How do we handle artist pics?

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#40]
Hi,
just a question, I wrote a function to compensate for missing artist profile pics with Twitter handles and Gravatars (see it [here](https://github.com/RTLcoil/Turbulence/blob/gh-pages/wp/wp-content/themes/turbulence/content-artist.php#L35)) I saw you made some use of gravatar as well and even [made a filter for using our own pics](https://github.com/RTLcoil/Turbulence/blob/gh-pages/wp/wp-content/themes/turbulence/author-bio.php#L21). Since I don't want to break anything I would be happy to get your guidance on making sure my compensation function is called every time we're using a profile pic.
Thanks,
M

**Comment by YomesInc** [comment]
get_avatar( $email, $size = '200') - this will work

echo '<img src="https://twitter.com/' . $twitter . '/profile_image?size=original" class="artist-details__photo"></img>'; - while this won't

$twitter = get_field('twitter_link'); - this is going to be the link
if ($twitter == true ) - so this condition won't work
echo '<img src="https://twitter.com/' . $twitter . '/profile_image?size=original" class="artist-details__photo"></img>';  - while here we'll get a link in a link

**Comment by YomesInc** [comment]
https://www.dropbox.com/s/45gs78997tph2m9/Screenshot%202015-05-27%2007.40.58.png?dl=0

**Comment by mushon** [comment]
Rather than use $twitter_link as a link we should use it as a handle. As in:
`mushon`

rather than:
`http://twitter.com/mushon`

See it working here:
http://demo.rtl.co.il/turbulence/artist/mushon-zer-aviv/

**Comment by YomesInc** [comment]
Then this if ($twitter == true ) should be changed to if ($twitter), and fixed in other places where it is used, because at the moment there is a link.

**Comment by mushon** [comment]
we can keep the variable name as is

**Comment by YomesInc** [comment]
If there is nothing required from me at this point I'm assigning the ticket to you

**Comment by mushon** [comment]
I was asking about the way artist pics are implemented on the Homepage as I want to implement the same thing I did on the artist page on the HP too.

**Comment by YomesInc** [comment]
1. Then you'll have to change it here as well: content-commission.php - it's the commission page and there is also information about artists
2. /turbulence/page-templates/home.php - this is for the main
   http://gyazo.com/65dc51bc4b3a1edac5e77f286f964069
   thumbnail - image, which is visible right away (<img src=".....">)
   image - the path to the image

**Comment by YomesInc** [comment]
https://www.dropbox.com/s/4o2q8z2bqu2hsli/Screenshot%202015-05-27%2010.50.05.png?dl=0

**Comment by YomesInc** [comment]
Are we good with it? Assigning to you in the meanwhile.
