### ISSUE TITLE
Link to commission site isn't implemented

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#41]

**Comment by YomesInc** [comment]
What do you mean by commission site?

**Comment by mushon** [comment]
commission_link

that’s what should open when you click the “enter" link

**Comment by YomesInc** [comment]
Could you send a print screen?

**Comment by mushon** [comment]
Fixed it myself in https://github.com/RTLcoil/Turbulence/commit/ad5449cc5db92c331ade8d6ae3ca60d865c072a8

**Comment by YomesInc** [comment]
Great, thanks
