### ISSUE TITLE
Artists list don't show full list and is buggy

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#42]
http://prntscr.com/79x2b8
- [x] only 5 artists appear even though more than 452 are entered
- [x] the image appears in the wrong location
- [x] the profile images should still appear even if the artist thumbnail image wasn't entered (see [Adam Greenfield](http://demo.rtl.co.il/turbulence/artist/adam-greenfield/) and this issue: #40)

**Comment by YomesInc** [comment]
Could you check this one please?

**Comment by mushon** [comment]
yeah, I think I actually fixed some of it but forgot to update the status. Another ticket closed, Yay!

**Comment by YomesInc** [comment]
:)
