### ISSUE TITLE
Remove current commission from "Other possibly relevant commissions"

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#43]
http://prntscr.com/7a0a53

**Comment by YomesInc** [comment]
Please check

**Comment by mushon** [comment]
From the looks of this on the site and the commissions page this still is a problem.
Rather than try implementing it on your own I suggest you use some kind of Similar Posts plugin.

**Comment by YomesInc** [comment]
So you would like to remove this element on all the pages of the site?

**Comment by mushon** [comment]
No. 
I was just suggesting you implement this with a plug in so it works as it's supposed to - proposing possibly relevant commissions based on author and tags.

**Comment by YomesInc** [comment]
Oooh, I see. Ok, I will look into this.

**Comment by YomesInc** [comment]
Would this be ok?
http://demo.rtl.co.il/turbulence/wp-admin/options-general.php?page=crp_options

If yes, we'll commit it.

**Comment by mushon** [comment]
Yes, this looks like something that could probably do the trick.

**Comment by YomesInc** [comment]
Good, you can check it.

**Comment by mushon** [comment]
ok, cool.
Now you can implement the styling and functionality so it looks like it should and not like this:
http://prntscr.com/7bsqks
(screenshot taken from [here](http://demo.rtl.co.il/turbulence/commission/furious-7/))

**Comment by mushon** [comment]
Please make sure to implement the same hover popup from the homepage on the recommended commissions as well.

**Comment by YomesInc** [comment]
Could you check the styling?

**Comment by YomesInc** [comment]
Regarding the hover I think we have another ticket open, so I'm assigning this to you

**Comment by mushon** [comment]
@RTLcoil the styling is fine now, but I'm not seeing another ticket for implementing the hover, so you can close this whenever such a ticket is made or simply reassign to me after the hover is implemented. Thanks.

**Comment by YomesInc** [comment]
The hover ticket is here: https://github.com/RTLcoil/Turbulence/issues/49
As far as I know everything from the ticket I am commenting now in was done. Please verify and close.

**Comment by mushon** [comment]
yeap
