### ISSUE TITLE
Pack artist credits into a carousel

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#45]

**Comment by YomesInc** [comment]
Screenshot please

**Comment by mushon** [comment]
That’s my ticket :)

-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On May 28, 2015 at 10:26:01 PM, RTLcoil (notifications@github.com) wrote:

Screenshot please

**Comment by YomesInc** [comment]
Oh, sorry)

**Comment by mushon** [comment]
no longer relevant after artist credits redesign
