### ISSUE TITLE
Align map to center on viewport resize

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#47]
This is the problem I'm referring to:
![markerbug](https://cloud.githubusercontent.com/assets/27123/7685420/d4202df4-fd96-11e4-9aee-4d66181a186f.gif)
[See it here](http://demo.rtl.co.il/turbulence/artist/jeff-thompson/)

**Comment by YomesInc** [comment]
I know, very few will play with browser's width, so my reply stays the same:
"Unfortunately that's the best result I can achieve within the given timeframe. I do not have resources for this project to make it perfect, sorry Mushon, I understand that it can be improved but considering our situation it is good as it is."

**Comment by mushon** [comment]
I know you don't intend to fix this. I didn't assign it to you for that reason exactly.
It is assigned to the Next Tasks milestone because it is not a blocker for launch. So unless I assign you on something, don't feel obliged to respond.

**Comment by YomesInc** [comment]
Oh, sorry Mushon, I forgot we've discussed it.
