### ISSUE TITLE
Artist's commissions are missing from artist page

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#49]
See here: http://demo.rtl.co.il/turbulence/artist/jillian-mcdonald/
http://prntscr.com/7co0d6

**Comment by YomesInc** [comment]
Could you check?

**Comment by mushon** [comment]
It works, but please implement the small icon design from the mock ups. It should receive the same pop-ip treatment as in the homepage.

**Comment by YomesInc** [comment]
It is generated by the plugin, so if we change it like you ask - the next time the plugin will be updated it will return to what it is now. So we either should never update the plugin, or implement this change after each update, or look for an alternative now.

**Comment by YomesInc** [comment]
We can also disable updates for this plugin by pretending it's ours, but I don't think it's legal :)

**Comment by mushon** [comment]
@RTLcoil it's actually legal under the GPL license, so I think that would be the best way to go.

**Comment by YomesInc** [comment]
I'm on it

**Comment by YomesInc** [comment]
Looks like it fits the design. There is a type /commission/, where the relevant work is shown at the bottom http://demo.rtl.co.il/turbulence/commission/from-the-valley-of-the-deer/

and there's author's page /artist/, and their work is shown at the bottom http://demo.rtl.co.il/turbulence/artist/abe-linkoln/

**Comment by mushon** [comment]
Looks good. Could you please add the hover effect to the works on the artist page too?

**Comment by YomesInc** [comment]
Done, could you verify?

**Comment by mushon** [comment]
Well, I meant to only add the hovers, but I actually like it better that way. So closing. Thanks.
