### ISSUE TITLE
Commissions order inconsistancy

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#50]
There are problems with the way the commissions are ordered:
http://prntscr.com/7cnzlq

**Comment by mushon** [comment]
@RTLcoil I would appreciate any pointers with this one:
![](http://i.imgur.com/klL62Tt.png)

**Comment by YomesInc** [comment]
Let me get back to you on this

**Comment by YomesInc** [comment]
Fixed

**Comment by mushon** [comment]
Awesome!
