### ISSUE TITLE
Strip unicode accents from artist list

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#51]
Make sure names starting with an '' will appear on the 'E' list for example to avoid these situations:
http://prntscr.com/7cxv0b
I started looking into it and it seems like the solution should include [PHP iconv](http://www.ficgs.com/How-to-remove-accents-in-PHP-f3057.html)

**Comment by YomesInc** [comment]
Please check this and let me know

**Comment by mushon** [comment]
Done

**Comment by mushon** [comment]
It works, but please implement the small icon design from the mock ups. It should receive the same pop-ip treatment as in the homepage.
