### ISSUE TITLE
Isotype tag search returns multiple identical results

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#52]
http://prntscr.com/7cynvw (clicked the collaboration tag) 
This might be a result of the results showing both icon and icon+title.

+

When clicking the tag should add it to the search query (since searching for "collaboration" without clicking the tag doesn't give double results, it might be a nice way of fixing two issues in one blow)
http://prntscr.com/7cypgx

+

Note that icons+titles shows only icons and no titles

**Comment by YomesInc** [comment]
This http://prntscr.com/7cypgx happens because of this http://prntscr.com/7fcjmo
i-item can't be a link, because it has other links inside it whether those which appear instantly or appearing in dynamically created popups

**Comment by mushon** [comment]
ok, can you simply implement it without a link?

**Comment by RTLcoil** [comment]
Like that?

**Comment by YomesInc** [comment]
Yes. The tags issue was fixed in the meanwhile.

**Comment by YomesInc** [comment]
The link was fixed as well, please verify.

**Comment by mushon** [comment]
fixed and verified
