### ISSUE TITLE
Image / video caption missing from homepage

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#53]
The caption on the main page doesn't show:
http://prntscr.com/7fmlle
- [x] The caption on the homepage should say the name of the work and the name of the artist
- [ ] Inside the commissions pages the caption should be for the image caption + the name of the artist

**Comment by YomesInc** [comment]
Please check

**Comment by mushon** [comment]
The caption on the homepage is good.
On the commission page though it should use the image title and the artist credit:
http://prntscr.com/7guuok

**Comment by YomesInc** [comment]
You see why I needed a detailed brief of all pages? These fixes should've been avoided from the start by a proper brief.

**Comment by mushon** [comment]
Well, generally, I agree, but in this case it was clearly marked in the original designs. On the [home page](https://projects.invisionapp.com/d/main#/console/2403969/53588992/preview) and the [commission page](https://projects.invisionapp.com/d/main#/console/2403969/54322549/preview)

**Comment by YomesInc** [comment]
Well, this is the third time that we are changing this...

This is for the main: 
http://prntscr.com/7hi7u2
http://prntscr.com/7hi8dm

This is for commissions:
http://prntscr.com/7hi947
http://prntscr.com/7hi9an

**Comment by mushon** [comment]
I am sorry @RTLcoil but the design explicitly shows that:

[the homepage](https://projects.invisionapp.com/d/main#/console/2403969/53588992/preview)
should only show the panel with [the work title](http://prntscr.com/7hi8dm) + artist name. With no extra overlay on the image.

&

[the commission page](https://projects.invisionapp.com/d/main#/console/2403969/54322549/preview)
should use [the work title](http://prntscr.com/7hi8dm) + artist name as an overlay and the [image caption](http://prntscr.com/7hi9an) + artist name on the panel

I am sorry that this is something you're wasting time on. It was always designed like that and we discussed it explicitly over the phone when the designs were initially shared with you. Let's fix this and move on. :/

**Comment by YomesInc** [comment]
Yeah, probably I allowed a too big gap between our discussion and the execution and simply forgot (and I still don't remember). But in any case - could you check now if it's fine?

**Comment by mushon** [comment]
Perfect!
