### ISSUE TITLE
Optimize homepage load

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#58]
This could be done using both:
- [ ] lazy loading (as originally discussed)
- [ ] WordPress caching plugin

**Comment by mushon** [comment]
I think this was addressed, please confirm.
If there are any more instructions for setting this on the production server, please advise.

**Comment by YomesInc** [comment]
It was addressed and no further action from Jesse is required at this point.

**Comment by mushon** [comment]
cool
