### ISSUE TITLE
Transition from RTL testing server to Turbulence.org

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#59]
the time has come…

**Comment by YomesInc** [comment]
Uuh... big moment. Please send me all the accesses.

**Comment by mushon** [comment]
Working on it. Anyway I will send them the last invoice so we can start processing that part as well…

**Comment by YomesInc** [comment]
Sounds good

**Comment by mushon** [comment]
I sent you the WP credentials, let's address the last pending issue #58 and start the migration

**Comment by YomesInc** [comment]
Could you resend please? It appeared in my spam folder and I accidentally deleted it.

**Comment by YomesInc** [comment]
I still need an FTP access please.

**Comment by mushon** [comment]
I sent it on Wednesday, just resent now

**Comment by YomesInc** [comment]
Thanks Mushon

**Comment by mushon** [comment]
I think we can mark this as (finally) done.
