### ISSUE TITLE
Commissions on artist page and commission pages don't show frame type on hover

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#60]
From [Jillian Mcdonald's artist page](http://demo.rtl.co.il/turbulence/commission/stand-by-your-guns/):
![artist page](http://g.recordit.co/KZp1QqXgov.gif)

From the [Disco-nnect commission page](http://demo.rtl.co.il/turbulence/commission/disco-nnect/):
![commission page](http://g.recordit.co/9APQgsOrqI.gif)

On [the homepage](http://demo.rtl.co.il/turbulence/) it works "as advertised" - it shows the smartphone frame:
![homepage](http://g.recordit.co/y3VMwKKCJn.gif)

I think the problem is that the hover was implemented in different ways across the site. If you implement both using the JS from the homepage (that works well), and **make sure it also works as expected on mobile** I think it would be much more robust and functional.

Needless to say, I would appreciate a swift patch on this one as we're already installed on the production server. Thanks!

**Comment by YomesInc** [comment]
We've fixed device's icon on the artist's page http://prntscr.com/811lel
And icons on commission's page http://prntscr.com/811lxu

Let me know if you're satisfied with the outcome

**Comment by YomesInc** [comment]
For the mobile we've made sure the icon is shown and the gallery is opened

**Comment by mushon** [comment]
have you pushed your changes to the repo?

**Comment by mushon** [comment]
@RTLcoil I haven't seen a change in the repo and this doesn't seem fixed on the site. I'm assuming the changes were pushed to the server without being committed to the repo, so you will have to merge them with the latest version.

**Comment by YomesInc** [comment]
Yes, pushed. My phpist though have to add in block related on commissions and artist pages 
http://prntscr.com/81jnzu
div class=i-item__popup-frame move to the link

but the phpist who worked on this project is on vacation now, so I'm short on php until the week of 16th.

**Comment by mushon** [comment]
Not sure I understand the question

**Comment by YomesInc** [comment]
It's not a question, just letting you know I'm short on php force at the moment and will get to this asap. In general - the front end was already pushed, so the answer to your question would be "yes".

**Comment by mushon** [comment]
yes `.i-item__popup-frame` moved into the link. I've now made sure it is consistent throughout the site and it seems to have fixed the clickability problem. Now you only need to make sure that in mobile the popup opens on the artist and commission pages just like it opens on the homepage. I believe that's a JS issue.

**Comment by YomesInc** [comment]
Yeah, we need the http://prntscr.com/81jnzu
div class=i-item__popup-frame in the link there on those pages. I'm not sure if ti's JS, might be, but it's assigned to my PHPst now.

**Comment by mushon** [comment]
What I'm saying is I moved `.i-item__popup-frame` into the link myself. Your PHP guy doesn't need to do that. Simply pull the latest commit and apply your JS changes there.

**Comment by YomesInc** [comment]
Aha, I see. This was done, could you check?

**Comment by mushon** [comment]
The thumbnails are clickable but clicking them opens the page directly rather than show the commission popups like they do on the homepage. The expected behavior is equal to that of the homepage.

**Comment by YomesInc** [comment]
Hm... I do see the hover, could you send me a print screen of the element which doesn't have it?

**Comment by mushon** [comment]
Here are the (commission and artist) screens where this behavior is expected but doesn't happen. I've tested on Mobile Safari on IPhone 5s.

**Comment by mushon** [comment]
and now with the pics:
![2015-08-11 18 03 32](https://cloud.githubusercontent.com/assets/27123/9201179/4f20e0f2-4054-11e5-9c8d-ae047afaad47.png)
![2015-08-11 18 04 00](https://cloud.githubusercontent.com/assets/27123/9201180/4f515f66-4054-11e5-8f2e-b2ffa4638c33.png)

**Comment by YomesInc** [comment]
Got you, I overlooked you are referring to mobile.
Is it ok now?

**Comment by mushon** [comment]
Yeap, thanks.
