### ISSUE TITLE
Allow a do-not-stretch option to gallery images

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#61]
This one has fallen through the cracks…
We've discussed the implementation of custom background color per-image but right now every image is stretched to fill the frame which means portrait images are brutally cropped and small images are stretched in very unpleasant ways. We have failed to identify this earlier as we've only tested with large and wide images.
My proposed solution: 
- implement a 'do-not-stretch' toggle on the image repeater and 
- implement an 'image-for-main-gallery' toggle to choose which image to use there (rather than use the featured image that doesn't necessarily fit the task)

I implemented the fields as reference:
<img alt="fields" src="https://cloud.githubusercontent.com/assets/27123/9025444/3dfeb4f0-390d-11e5-8c25-78978433ae1d.png">

By the way, this approach also allows us to get rid of redundancies and drop these two fields, as both will be handled by the repeater:
<img alt="screenshot at aug 02 11-56-08" src="https://cloud.githubusercontent.com/assets/27123/9025455/a1e68ace-390d-11e5-819b-6993ee811036.png">

Now we need to hook it to the home page and commission page galleries. Thanks.

**Comment by YomesInc** [comment]
Could you show me an example of a small image stretched? I remember that we applied a fix for this.
In terms of big images - I also remember that that's what you and I agreed at some stage.

Please elaborate

**Comment by mushon** [comment]
Yes, here's the example:
http://demo.rtl.co.il/turbulence/commission/from-the-valley-of-the-deer/

In the first image's case if the do-not-streatch checkbox is checked the image should be centered in the middle of the frame with the background color surrounding it.

Right now it looks like this:
http://prntscr.com/7zx2a6

when what we want is for it to look like this:
http://prntscr.com/7zx3he

It is simply a matter of toggling one CSS property:
http://prntscr.com/7zx42o

Thanks.

**Comment by YomesInc** [comment]
Regarding cropping - that's what you've asked https://www.dropbox.com/s/vqbmyxof1tta73b/Screenshot%202015-08-02%2008.55.23.png?dl=0

and further in the same discussion I thought we've closed everything...?

**Comment by mushon** [comment]
Please note, the discussion you referred to does not refer to the main gallery or the commission gallery, but to the popup and to the home-slides.

**Comment by mushon** [comment]
To simplify things, I would recommend all galleries (including the home-slides gallery) adopt the same functionality as I described above.

**Comment by YomesInc** [comment]
It's still a change in behavior and I consider it as something additional. As an option, we can add a checkbox in the admin allowing to choose whether the image should fill 100% http://prntscr.com/80m15f or keep its original size http://prntscr.com/80m1wb
but that's also and add on, so let me know how you would like to proceed from here.

**Comment by mushon** [comment]
Well, I don’t see it as an add-on, but let me try fixing it myself.

**Comment by YomesInc** [comment]
Just because we've dedicated to this issue too much time because it wasn't defined clear enough in the beginning. Please close with them some maintenance budget because usually additional requests continue to flow, especially shortly after launch.

**Comment by mushon** [comment]
I will look into it, but I doubt such budget would be available. Will keep you posted.

**Comment by mushon** [comment]
I fixed it myself in f99c58f9a22d43528ceede7cf5cb7ca125267f85 (kinda proud of myself actually)
