### ISSUE TITLE
Separate non-commission pages to different URLs

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#62]
For example:
http://dev.turbulence.org/commission/pop-up-3/

being a guest curated exhibition should be:
http://dev.turbulence.org/exhibition/pop-up-3/

*This is a fix we should have included earlier and is needed for the simplification we made when we decided that all projects will appear as commissions

**Comment by YomesInc** [comment]
I'm not sure what’s the ask and how is this related to the development rather than to maintenance.

**Comment by mushon** [comment]
won't fix
