### ISSUE TITLE
Change url from /commission/ to /project/

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#63]
@RTLcoil I would appreciate some guidance on this one

**Comment by YomesInc** [comment]
You mean how and where to do that?

**Comment by YomesInc** [comment]
For one or all pages?

**Comment by mushon** [comment]
This is simply textual change. We want to use the term 'project' instead of the term 'commission' in the URL.

**Comment by mushon** [comment]
I found how to fix it through CPT UI
