### ISSUE TITLE
Add categories to projects filter

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#64]
Turbulence would like the categories to be added as filters here:
![categories_filter](https://cloud.githubusercontent.com/assets/27123/9098687/0eb7dd88-3bd4-11e5-9669-c167911aacc8.jpg)
so they can also be filtered by.

@RTLcoil any tips would be appreciated.

**Comment by YomesInc** [comment]
By "categories" you mean something from the database or you would just like the option to type it manually?

**Comment by mushon** [comment]
By Categories I mean the native WordPress categories. We use: 
- commissions
- events
- exhibitions
- commissioned texts
- artist studio visit
- spotlight
- other text
- …

**Comment by mushon** [comment]
I did it (!)

**Comment by mushon** [comment]
https://github.com/RTLcoil/Turbulence/commit/85aefc081b8be58da7bd8f46f3d5bd17c51720ef

**Comment by YomesInc** [comment]
:) way to go
