### ISSUE TITLE
Communication between tags and searchbox is only one way

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#65]
![one way](recordit.co/cuIrGT44eD.gif)

Clicking a tag or category from the panel adds it to the search field, but clicking it again should take it off of there and it doesn't, moreover, clicking again adds it again. This is a bug or simply a feature that was not implemented completely. Please look into fixing it

**Comment by YomesInc** [comment]
We've discussed it and that's the way we agreed it will be - just a textual value added to the search field, not an actual tag.

**Comment by mushon** [comment]
Well, although I see this as the completion of a currently not-fully-implemented feature I understand this is something I have not discussed with you in full and hence I agree we might want to use the maintenance budget for it. If you agree I will make sure to fully define the functionality.

**Comment by YomesInc** [comment]
Yes, if you could define it in detail that would be great.
Thanks Mushon

**Comment by mushon** [comment]
OK…
1. I click a tag1
2. Tag1 appears as a tag (frame and all) within the search field and the projects list is filtered
3. The tag list is then minimized to include only other tags that are assigned to projects together with tag1
4. I click tag2
5. Tag2 appears as well on the search box as a tag next to the tag1 and filters the list to only show projects that hold both tags
6. The tag list is then minimized again to include only other tags that are assigned to projects together with both tag1 & tag2
7. I click on tag1 again
8. Tag1 is removed from the search box, and now the commission list shows every project that is assigned together with tag2
9. The tags list also expands to show every tag that is assigned on a project with tag2
10. I write free text next to tag2, it filters the list of projects tagged with tag2 to show only those who also respond to the search-term I entered.
11. I backspace over tag2's last character and it deletes the whole tag also unchecking it from the tag list
12. The commission list is filtered by the free text
13. The tag list shows only tags that correspond with the free text entry

*please note that the tags also include categories now but as far as JS is concerned they are the same

Please log your hours and report back, I will let Turbulence know you'll be working on this one as an extra maintenance thing. Thanks.

**Comment by YomesInc** [comment]
3."Together with tag1" but without showing the tag1 itself, because it already appears in the search field, right? Or do you still want it to appear at the bottom with other tags? If yes - you didn't describe the look of the chosen tag.

7.If the first statement of my previous question is right, then why "again"? It would be the first time that you click on tag1 in this location (the search field).

So the categories do not influence the search in any way?

**Comment by mushon** [comment]
3.Yes, I still want it to appear underneath in the tags panel (mockup below)

7.When you click on tag1 "again" not within the search field it will toggle the tag and remove it from the search field. By contrast, clicking the bigger tag that's within the search field will select it and allow to remove it by clicking backspace. Doing this will also unselect it in the tags panel.

The categories definitely influence the search, in exactly the same way as the tags. JS-wise they are the exact same thing, their only difference is in their position (appear first) and styling.

Here's a mockup:
![search](https://cloud.githubusercontent.com/assets/27123/9115609/bf95d62a-3c68-11e5-9660-df2a55aa84a9.jpg)

**Comment by YomesInc** [comment]
Thanks Mushon, could you describe the behavior when adding a tag to the search field (step 2)? I don't see any change in color or any other UX changes described once the tag is added, so please elaborate.

**Comment by mushon** [comment]
When a tag is clicked, say [pop up]:
- it gets the "chosen" class like it does now which makes it a bit darker than the rest of the tags
- it is replicated in a 150% larger version of its chosen self into the search bar and is prepended to the query
- the list of icons below is filtered
- the list of tags is filtered to show only other tags (and categories) that if added to the query above will provide results

Kapish?

**Comment by YomesInc** [comment]
Almost, could you show how this one will look? "it is replicated in a 150% larger version of its chosen self into the search bar and is prepended to the query" because usually there is an "x" button on it. It's also not clear if I can click on that tag and what happens then.

**Comment by mushon** [comment]
We can go with the  option of having the x button on the tags, you can add it in there and I will style it.

**Comment by YomesInc** [comment]
Could you check

**Comment by mushon** [comment]
Looking good. 

Two more issues I'm seeing:
1. Drop down text looks weird. It should autocomplete, titles, tags and names and not show all of them together:
![image](https://cloud.githubusercontent.com/assets/27123/9282990/d8e07e5c-42d8-11e5-9f9c-4cecc04e67f2.jpg)
2. We have tags in the commission popups. In the Ho,epage, clicking them rather than taking us to the tag archive, should add the tag to the query.

**Comment by YomesInc** [comment]
Should the search be performed by all three below, which are:
1 tags
2 commission name
3 category
?

**Comment by mushon** [comment]
Yes + artist

**Comment by YomesInc** [comment]
Ok, so when I type something that is found in tags of the commission - should we only show that particular tag as an autocomplete or commission's title or anything else?

**Comment by mushon** [comment]
If you type `text` for example you should get:
(text)                      <—tag
[commissioned text]         <—category
[  ] Two Textual Instruments       <—commission title
(  ) Abraham Textosorous       <—artist name (fake)

Commission titles that do not have the word `text` in them should not appear in the autocomplete. Makes sense?

**Comment by YomesInc** [comment]
It does, but if we have several search results? Or the query is not complete (let's say "te")?

**Comment by mushon** [comment]
Start with categories, then tags, then titles. Start filtering from 3 characters (don't start filtering at "te" but at "tex")

**Comment by YomesInc** [comment]
So first we'll show all categories from all search results, then tags from all search results, then titles, then artists? I'm still struggling to imagine how will that look...

**Comment by mushon** [comment]
It would simply show categories, tags, artist names and commission titles the autocomplete list with each getting its custom design (the square blue frame for categories, the rounded gray frames for the tags, the round profile image to the left of the artist name and the free text for the commission title. If any of them is clicked, they are added to the search box's input field and the list of items is then filtered accordingly.

**Comment by YomesInc** [comment]
Could you visualize it please?

**Comment by mushon** [comment]
Here you go:
![autocomplete](https://cloud.githubusercontent.com/assets/27123/9351202/237b6668-4660-11e5-97e8-104ffc64f9ae.png)

**Comment by mushon** [comment]
by the way, clicking on `Alfred Texas` will present all the works he is associated with + his profile link
and clicking `Two Textual Instruments` will present that work and the profile links for the artists involved with it

**Comment by mushon** [comment]
& I would love for you to implement the same dropdown in the other search box throughout the site

**Comment by YomesInc** [comment]
This looks good if there are not many search results, but how will it look if we have 10 search results per each (category, tag, artist, and commission)?

**Comment by mushon** [comment]
we can limit the height of the autocomplete and allow keyboard interaction and scroll (that’s how it’s usually done anyway, I obviously haven’t invented it)

**Comment by YomesInc** [comment]
I can't recall I saw this type of search showing tags, categories, and other search results in one autocomplete window... So you'd like to enable vertical scroll in there, so that if 20 tags and categories push other search results down - you can scroll there? What will be the height of that autocomplete element in total then?

**Comment by mushon** [comment]
In total it depends on the number of the results. the `overflow: hidden` box should be the same height as it is right now, it already allows scroll inside that box. What needs to change is that autocomplete options should not start before at least 3 characters have been typed.

**Comment by YomesInc** [comment]
Got it, leave it with me and let's see what I come up with.
