### ISSUE TITLE
items within years are unsorted

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#66]
The commissions grid works well for sorting years but doesn't sort the dates within these years correctly:
![commissions_sort](https://cloud.githubusercontent.com/assets/27123/9872362/933bacc8-5ba1-11e5-891d-70ab1c122cfd.jpg)

@RTLcoil please fix this promptly as we would like to launch next week (!)

**Comment by YomesInc** [comment]
Please check

**Comment by mushon** [comment]
the sorting has indeed changed but this still seems to not be sorted in reverse chronological order based on launch date. For example, in 2015 the March release appears before April and in 2014 the first item was released in February.

**Comment by YomesInc** [comment]
Check again please

**Comment by mushon** [comment]
Looking good now. Thanks.
