### ISSUE TITLE
make gh-pages the default branch in the repo

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#8]
you can then discard the 'master' branch

**Comment by mushon** [comment]
@RTLcoil please merge my commits on the gh-pages branch and use it as the default branch so we can follow the updates on http://RTLcoil.github.io/Turbulence

**Comment by mushon** [comment]
@timon188 this might be on your plate.

**Comment by mushon** [comment]
This was not addressed

**Comment by YomesInc** [comment]
Please provide me with more information here

**Comment by mushon** [comment]
I can also do it if you give me admin rights to the repo. 

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon

**Comment by YomesInc** [comment]
Sure, how do I do that?

**Comment by mushon** [comment]
In the repo settings but it's not super urgent. 

Mushon Zer-Aviv
Mushon.com | Shual.com | @Mushon
