### ISSUE TITLE
HP commissions and artists pop-overs should appear on :hover

### ISSUE THREAD

**Issue by mushon** [RTLcoil/Turbulence#9]
A click should take to the artist/commission page.

On touch devices they should require a single click, with the second click taking to the artist/commission page.

(right now opening the pop-over requires a double click)

**Comment by YomesInc** [comment]
For mobile it opens the gallery and then by clicking on one of the images it goes to that commission http://prntscr.com/6knnuz
Would you like to change that?
Also, it wasn't in the design but if we are already speaking - perhaps for an artist and for a commission with a name it would be better to make a gallery on mobile?

**Comment by mushon** [comment]
Yes, let's keep this behavior on mobile and expand it to the other tabs as you rightfully suggested. The note about hover referred to the interaction in the desktop. 

Cheers,

Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

**Comment by YomesInc** [comment]
Thanks Mushon.
Regarding the second question - yes, I know that it's for mobile, I was just wondering if we should create galleries for artists and commissions on mobiles as well.

**Comment by mushon** [comment]
Yes please

**Comment by mushon** [comment]
fixed.
